#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""FM1 Quest: bake assets/quest/sprites.json (palette-indexed frames, made by quest/web/tools/bake_sprites.js from the
design's procedural sprites) into a C header: tools/gen_quest_sprites.py build/gen/felucca_qsprites.h
per frame: w*h palette indices, 4 bits each (high nibble first), then a w*h bit mask (1 = opaque), rows left to right."""
import base64, json, sys
from pathlib import Path
src = json.loads((Path(__file__).resolve().parents[1] / "assets" / "quest" / "sprites.json").read_text())
data, rows, names = [], [], []
for f in src["frames"]:
    raw = base64.b64decode(f["data"])
    n = f["w"] * f["h"]
    assert len(raw) == n
    rows.append((f["ox"], f["oy"], f["w"], f["h"], len(data)))
    names.append(f["name"].upper())
    px = [0 if v == 255 else v for v in raw] + [0]
    data += [(px[i] << 4) | px[i + 1] for i in range(0, n, 2)]                   # 4 bits per pixel, high nibble first
    mask = [1 if v != 255 else 0 for v in raw] + [0] * (-n % 8)
    data += [sum(b << (7 - j) for j, b in enumerate(mask[i:i + 8])) for i in range(0, len(mask), 8)]   # then 1 bit per pixel: opaque
assert len(data) < 65536
L = ["/* generated by tools/gen_quest_sprites.py */", "#pragma once", "#include <stdint.h>",
     "typedef struct { int8_t ox, oy; uint8_t w, h; uint16_t off; } qspr_t;", "enum {"]
L += [f"    QS_{n}," for n in names] + ["    QS_COUNT", "};"]
L.append(f"static const uint8_t QSPR_DATA[{len(data)}] = {{")
for i in range(0, len(data), 32):
    L.append("    " + ",".join(str(b) for b in data[i:i + 32]) + ",")
L.append("};")
L.append("static const qspr_t QSPR[QS_COUNT] = {")
L += [f"    {{{ox}, {oy}, {w}, {h}, {off}}}," for ox, oy, w, h, off in rows]
L.append("};")
Path(sys.argv[1]).write_text("\n".join(L) + "\n")
print(f"quest sprites: {len(rows)} frames, {len(data)} B")
