#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""FM1 Quest title screen (README: TITLE): assets/quest/title-bg-240.png (the design's illustration, reduced to 240x240) quantized to
the 16-colour scene palette with a 4x4 ordered dither at 120 x 120, packed 4 bits per pixel (7.2 KB, drawn doubled); assets/quest/logo-340.png (white
"FM1 QUEST", transparent) reduced to ~170 px wide as a 1-bit mask (the screen draws it cream with a dark outline).
tools/gen_quest_title.py build/gen/felucca_qtitle.h"""
import sys
from pathlib import Path
from PIL import Image
A = Path(__file__).resolve().parents[1] / "assets" / "quest"
PAL = ["1a1016", "2b2338", "5a3050", "2f4a3a", "6a4030", "4a3c48", "a89aa0", "f2e2c4", "c8443c", "e08a3a", "f0c860", "6a9a4a", "4a78b0", "8a6a9a", "e09090", "f0b890"]
PAL = [tuple(int(h[i:i + 2], 16) for i in (0, 2, 4)) for h in PAL]
BAYER = [0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5]
BG = 120                                     # the art is kept at 120 x 120 (7.2 KB) and drawn doubled: flash space (the app has ~560 KiB)
bg = Image.open(A / "title-bg-240.png").convert("RGB").resize((BG, BG), Image.LANCZOS)
px = bg.load()
idx = []
for y in range(BG):
    for x in range(BG):
        th = (BAYER[(y % 4) * 4 + x % 4] / 16 - 0.5) * 28
        r, g, b = (px[x, y][i] + th for i in range(3))
        best = min(range(16), key=lambda k: (r - PAL[k][0]) ** 2 * .3 + (g - PAL[k][1]) ** 2 * .59 + (b - PAL[k][2]) ** 2 * .11)
        idx.append(best)
packed = [(idx[i] << 4) | idx[i + 1] for i in range(0, len(idx), 2)]
logo = Image.open(A / "logo-340.png").convert("RGBA")
lw = 170
lh = round(logo.height * lw / logo.width)
logo = logo.resize((lw, lh), Image.LANCZOS)
la = logo.split()[3]
mask = []
for y in range(lh):
    row = 0
    bits = []
    for x in range(lw):
        bits.append(1 if la.getpixel((x, y)) >= 110 else 0)
    bits += [0] * (-len(bits) % 8)
    for i in range(0, len(bits), 8):
        mask.append(sum(b << (7 - j) for j, b in enumerate(bits[i:i + 8])))
L = ["/* generated by tools/gen_quest_title.py */", "#pragma once", "#include <stdint.h>",
     f"#define QTITLE_BGW {BG}", f"#define QTITLE_LOGO_W {lw}", f"#define QTITLE_LOGO_H {lh}", f"#define QTITLE_LOGO_ROW {(lw + 7) // 8}",
     f"static const uint8_t QTITLE_BG[{len(packed)}] = {{"]
L += ["    " + ",".join(str(b) for b in packed[i:i + 32]) + "," for i in range(0, len(packed), 32)]
L += ["};", f"static const uint8_t QTITLE_LOGO[{len(mask)}] = {{"]
L += ["    " + ",".join(str(b) for b in mask[i:i + 32]) + "," for i in range(0, len(mask), 32)]
L += ["};"]
Path(sys.argv[1]).write_text("\n".join(L) + "\n")
print(f"quest title: bg {BG}x{BG} {len(packed)} B, logo {lw}x{lh} {len(mask)} B")
