#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""FM1 Quest: bake assets/quest/sprites.json (palette-indexed frames, made by quest/web/tools/bake_sprites.js from the
design's procedural sprites) into a C header: tools/gen_quest_sprites.py build/gen/felucca_qsprites.h
255 = transparent, 0..15 = the 16-colour scene palette (QPAL in ui_quest.c)."""
import base64, json, sys
from pathlib import Path
src = json.loads((Path(__file__).resolve().parents[1] / "assets" / "quest" / "sprites.json").read_text())
data, rows, names = [], [], []
for f in src["frames"]:
    raw = base64.b64decode(f["data"])
    assert len(raw) == f["w"] * f["h"]
    rows.append((f["ox"], f["oy"], f["w"], f["h"], len(data)))
    names.append(f["name"].upper())
    data += list(raw)
assert len(data) < 65536
L = ["/* generated by tools/gen_quest_sprites.py */", "#pragma once", "#include <stdint.h>",
     "typedef struct { int8_t ox, oy; uint8_t w, h; uint16_t off; } qspr_t;", "enum {"]
L += [f"    QS_{n}," for n in names] + ["    QS_COUNT", "};"]
L.append(f"static const uint8_t QSPR_DATA[{len(data)}] = {{")
for i in range(0, len(data), 32):
    L.append("    " + ",".join(str(b) for b in data[i:i + 32]) + ",")
L.append("};")
L.append("static const qspr_t QSPR[QS_COUNT] = {")
L += [f"    {{{ox}, {oy}, {w}, {h}, {off}}}," for ox, oy, w, h, off in rows]
L.append("};")
Path(sys.argv[1]).write_text("\n".join(L) + "\n")
print(f"quest sprites: {len(rows)} frames, {len(data)} B")
